# -*- coding: utf-8 -*-
"""
build.py — one-click PyInstaller build for POI Scanner.

Usage
-----
  Normal build:
    python build.py

  Debug build (keeps console open on crash, verbose imports):
    python build.py --debug

Output
------
  dist/POIScanner/
    POIScanner.exe   <- the executable
    config.ini       <- copy of your config (edit credentials before running)
    startup_error.log  <- written automatically if the exe crashes at startup
    poi_scanner.log    <- written by the scanner during normal operation
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path

HERE      = Path(__file__).resolve().parent
MAIN      = HERE / "main.py"
SPEC_FILE = HERE / "poi_scanner.spec"
DIST_DIR  = HERE / "dist" / "POIScanner"
CONFIG    = HERE / "config.ini"
DEBUG     = "--debug" in sys.argv


# ---------------------------------------------------------------------------
# 1. Ensure PyInstaller
# ---------------------------------------------------------------------------
def ensure_pyinstaller():
    try:
        import PyInstaller  # noqa: F401
        print("[OK] PyInstaller already installed.")
    except ImportError:
        print("[..] Installing PyInstaller...")
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "pyinstaller"],
            stdout=subprocess.DEVNULL,
        )
        print("[OK] PyInstaller installed.")


# ---------------------------------------------------------------------------
# 2. Write .spec
# ---------------------------------------------------------------------------
def write_spec():
    debug_flag = "True" if DEBUG else "False"

    spec = f'''\
# -*- mode: python ; coding: utf-8 -*-
# POI Scanner — auto-generated by build.py  (debug={debug_flag})

block_cipher = None

hidden_imports = [
    # ---- aiohttp and its dependencies ------------------------------------
    "aiohttp",
    "aiohttp._helpers",
    "aiohttp._websocket",
    "aiohttp.abc",
    "aiohttp.client",
    "aiohttp.client_exceptions",
    "aiohttp.client_reqrep",
    "aiohttp.client_ws",
    "aiohttp.connector",
    "aiohttp.cookiejar",
    "aiohttp.formdata",
    "aiohttp.http_parser",
    "aiohttp.http_websocket",
    "aiohttp.http_writer",
    "aiohttp.log",
    "aiohttp.multipart",
    "aiohttp.payload",
    "aiohttp.resolver",
    "aiohttp.streams",
    "aiohttp.tcp_helpers",
    "aiohttp.tracing",
    "aiohttp.typedefs",
    "aiohttp.web",
    "aiosignal",
    "frozenlist",
    "frozenlist._frozenlist",
    "multidict",
    "multidict._multidict",
    "yarl",
    "async_timeout",
    "attr",
    "attrs",
    # ---- requests and its dependencies ----------------------------------
    "requests",
    "requests.adapters",
    "requests.auth",
    "requests.cookies",
    "requests.exceptions",
    "requests.models",
    "requests.sessions",
    "requests.structures",
    "requests.utils",
    "urllib3",
    "urllib3.contrib",
    "urllib3.contrib.socks",
    "urllib3.util",
    "urllib3.util.retry",
    "urllib3.util.ssl_",
    "certifi",
    "charset_normalizer",
    "charset_normalizer.md__mypyc",
    "idna",
    # ---- numpy ----------------------------------------------------------
    "numpy",
    "numpy.core",
    "numpy.core._methods",
    "numpy.lib.format",
    "numpy.lib.stride_tricks",
    "numpy.random",
    "numpy.random._common",
    "numpy.random._bounded_integers",
    "numpy.random._generator",
    "numpy.random.bit_generator",
    # ---- pandas ---------------------------------------------------------
    "pandas",
    "pandas._libs",
    "pandas._libs.tslibs",
    "pandas._libs.tslibs.np_datetime",
    "pandas._libs.tslibs.nattype",
    "pandas._libs.tslibs.timestamps",
    "pandas._libs.tslibs.timedeltas",
    "pandas._libs.tslibs.offsets",
    "pandas._libs.tslibs.period",
    "pandas._libs.tslibs.strptime",
    "pandas._libs.tslibs.parsing",
    "pandas._libs.tslibs.tzconversion",
    "pandas.core.arrays",
    "pandas.core.arrays.integer",
    "pandas.core.arrays.floating",
    "pandas.core.indexes",
    "pandas.io.formats.style",
    "pytz",
    "dateutil",
    "dateutil.tz",
    "dateutil.tz.tz",
    "six",
    # ---- sqlite3 --------------------------------------------------------
    "sqlite3",
    "_sqlite3",
    # ---- asyncio (Windows sometimes misses these) -----------------------
    "asyncio",
    "asyncio.base_events",
    "asyncio.events",
    "asyncio.futures",
    "asyncio.locks",
    "asyncio.queues",
    "asyncio.streams",
    "asyncio.tasks",
    "asyncio.transports",
    "asyncio.windows_events",
    "asyncio.proactor_events",
    "asyncio.selector_events",
    # ---- stdlib used by project -----------------------------------------
    "configparser",
    "hmac",
    "hashlib",
    "json",
    "math",
    "threading",
    "concurrent.futures",
    "logging",
    "logging.handlers",
    "ctypes",
    "ctypes.wintypes",
    # ---- tkinter (GUI) --------------------------------------------------
    "tkinter",
    "tkinter.ttk",
    "tkinter.messagebox",
    "tkinter.font",
    # ---- our src package ------------------------------------------------
    "src",
    "src.trade_gui",
    "src.binance_data",
    "src.bybit_client",
    "src.config_loader",
    "src.detector",
    "src.indicators",
    "src.models",
    "src.scanner",
    "src.telegram_notifier",
    "src.trade_executor",
    "src.trade_store",
]

a = Analysis(
    ["main.py"],
    pathex=[SPECPATH],
    binaries=[],
    datas=[
        # Copy the entire src package into the bundle
        ("src", "src"),
    ],
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[
        "tkinter", "matplotlib", "scipy", "PIL", "cv2",
        "IPython", "jupyter", "notebook", "pytest",
        "setuptools", "distutils", "xmlrpc",
        "unittest", "doctest", "pdb", "profile",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="POIScanner",
    debug={debug_flag},
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,        # always keep console so logs are visible
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="POIScanner",
)
'''
    SPEC_FILE.write_text(spec, encoding="utf-8")
    print(f"[OK] Spec written: {SPEC_FILE}  (debug={DEBUG})")


# ---------------------------------------------------------------------------
# 3. Run PyInstaller
# ---------------------------------------------------------------------------
def run_pyinstaller():
    print("[..] Running PyInstaller — this takes 1-3 minutes...")
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--clean",
        "--noconfirm",
        str(SPEC_FILE),
    ]
    result = subprocess.run(cmd, cwd=str(HERE))
    if result.returncode != 0:
        print("\n[ERROR] PyInstaller failed — see output above.")
        sys.exit(1)
    print("[OK] Build complete.")


# ---------------------------------------------------------------------------
# 4. Post-build: copy config and write a launcher batch file
# ---------------------------------------------------------------------------
def post_build():
    DIST_DIR.mkdir(parents=True, exist_ok=True)

    # config.ini must sit NEXT TO the exe (in POIScanner/, NOT in _internal/).
    # PyInstaller puts all Python modules inside _internal/ but the exe itself
    # lives in POIScanner/ — that is where os.chdir() lands at runtime.
    config_dest = DIST_DIR / "config.ini"
    if CONFIG.exists():
        shutil.copy2(CONFIG, config_dest)
        print(f"[OK] config.ini -> {config_dest}")
        print(f"     (next to the exe, NOT inside _internal/)")
    else:
        print(f"[WARN] config.ini not found in project root.")
        print(f"       Copy it manually to: {config_dest}")

    # Write a .bat launcher for convenience (Windows)
    bat = DIST_DIR / "Run_POIScanner.bat"
    bat.write_text(
        '@echo off\n'
        'cd /d "%~dp0"\n'
        'POIScanner.exe\n'
        'if %ERRORLEVEL% NEQ 0 (\n'
        '    echo.\n'
        '    echo Scanner exited with error %ERRORLEVEL%\n'
        '    echo Check startup_error.log in this folder.\n'
        '    pause\n'
        ')\n',
        encoding="utf-8",
    )
    print(f"[OK] Run_POIScanner.bat written (double-click this to start)")


# ---------------------------------------------------------------------------
# 5. Summary
# ---------------------------------------------------------------------------
def print_summary():
    print()
    print("=" * 62)
    print("  BUILD COMPLETE" + ("  [DEBUG MODE]" if DEBUG else ""))
    print("=" * 62)
    print(f"  Folder  : {DIST_DIR}")
    print(f"  Launch  : double-click  Run_POIScanner.bat")
    print(f"         or run           POIScanner.exe  in that folder")
    print()
    print("  BEFORE RUNNING — edit dist/POIScanner/config.ini:")
    print("    [TELEGRAM]  bot_token / chat_id")
    print("    [BYBIT]     api_key / api_secret")
    print()
    print("  If it crashes:")
    print("    1. Check  startup_error.log  (written automatically)")
    print("    2. Rebuild with:  python build.py --debug")
    print("       (shows verbose import trace in the console)")
    print("=" * 62)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    os.chdir(HERE)
    print()
    print("POI Scanner — Build Script")
    print(f"Mode : {'DEBUG' if DEBUG else 'RELEASE'}")
    print("-" * 40)
    ensure_pyinstaller()
    write_spec()
    run_pyinstaller()
    post_build()
    print_summary()
